name: Test

on: [ 'push', 'pull_request', 'workflow_dispatch' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        node_version: [ '14', '16' ]
        architecture: [ 'x64' ]
    name: Node ${{ matrix.node_version }}_${{ matrix.architecture }} on ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      
      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm ci --force
      
      - name: Install library dependencies
        run: cd projects/ngx-crud-forms && npm ci --force

      - name: Build ngx-crud-forms
        run: cd ../.. && ng build ngx-crud-forms
      
      - name: Create local link to ngx-crud-forms
        run: cd dist/ngx-crud-forms && npm link

      - name: Link ngx-crud-forms to wrapper project
        run: cd ../.. && npm link ngx-crud-forms 

      - name: Run specs
        run: npm run test -- ngx-crud-forms --browsers ChromeHeadless --watch false
